### ISSUE TITLE
NoMethodError: private method `select' called for nil:NilClass

### ISSUE THREAD

**Issue by hasegeli** [deanwilson/puppet-lint-explicit_hiera_class_param_lookup-check#7]
```
NoMethodError: private method `select' called for nil:NilClass
/var/lib/gems/2.1.0/gems/puppet-lint-explicit_hiera_class_param_lookup-check-0.1.1/lib/puppet-lint/plugins/explicit_hiera_class_param_lookup.rb:5:in `block in check'
/var/lib/gems/2.1.0/gems/puppet-lint-explicit_hiera_class_param_lookup-check-0.1.1/lib/puppet-lint/plugins/explicit_hiera_class_param_lookup.rb:3:in `each'
/var/lib/gems/2.1.0/gems/puppet-lint-explicit_hiera_class_param_lookup-check-0.1.1/lib/puppet-lint/plugins/explicit_hiera_class_param_lookup.rb:3:in `check'
/var/lib/gems/2.1.0/gems/puppet-lint-2.3.3/lib/puppet-lint/checkplugin.rb:21:in `run'
/var/lib/gems/2.1.0/gems/puppet-lint-2.3.3/lib/puppet-lint/checks.rb:60:in `block in run'
/var/lib/gems/2.1.0/gems/puppet-lint-2.3.3/lib/puppet-lint/checks.rb:57:in `each'
/var/lib/gems/2.1.0/gems/puppet-lint-2.3.3/lib/puppet-lint/checks.rb:57:in `run'
/var/lib/gems/2.1.0/gems/puppet-lint-2.3.3/lib/puppet-lint.rb:196:in `run'
/var/lib/gems/2.1.0/gems/puppet-lint-2.3.3/lib/puppet-lint/bin.rb:59:in `block in run'
/var/lib/gems/2.1.0/gems/puppet-lint-2.3.3/lib/puppet-lint/bin.rb:56:in `each'
/var/lib/gems/2.1.0/gems/puppet-lint-2.3.3/lib/puppet-lint/bin.rb:56:in `run'
/var/lib/gems/2.1.0/gems/puppet-lint-2.3.3/bin/puppet-lint:7:in `<top (required)>'
/usr/local/bin/puppet-lint:23:in `load'
/usr/local/bin/puppet-lint:23:in `<main>'
```

**Comment by deanwilson** [comment]
Hi @hasegeli,

Can you tell me the ruby version you're seeing this on please? Also do you have a small puppet manifest that triggers the stack track?

Thank you for raising this,

**Comment by hasegeli** [comment]
puppet-lint version: 2.3.3
ruby version: 2.1.5-p273
platform: x86_64-linux-gnu
file path: freebsd.pp
file contents:
```
class ig::base::freebsd inherits ig::base {
}
```

**Comment by deanwilson** [comment]
That's brilliant, thank you. I have fix but i want to double check something before I do a new release.

https://github.com/deanwilson/puppet-lint-explicit_hiera_class_param_lookup-check/compare/fix-issue-7 should hopefully fix it for you.

**Comment by deanwilson** [comment]
I've pushed the release containing the fix to rubygems. Thanks again for reporting this, and the debug information.
